export interface SuggestedGoal {
  title: string;
  category: string;
}

export const SUGGESTED_GOALS: Record<string, SuggestedGoal[]> = {
  'Academic Excellence': [
    { title: 'Achieve 4.0 GPA this semester', category: 'Academic Excellence' },
    { title: 'Make Dean\'s List', category: 'Academic Excellence' },
    { title: 'Complete honors thesis', category: 'Academic Excellence' },
    { title: 'Publish research paper', category: 'Academic Excellence' },
    { title: 'Present at academic conference', category: 'Academic Excellence' },
    { title: 'Win academic competition', category: 'Academic Excellence' },
    { title: 'Get straight A\'s in major courses', category: 'Academic Excellence' },
    { title: 'Complete independent study project', category: 'Academic Excellence' },
    { title: 'Earn academic scholarship', category: 'Academic Excellence' },
    { title: 'Join honor society', category: 'Academic Excellence' },
    { title: 'Become teaching assistant', category: 'Academic Excellence' },
    { title: 'Master difficult subject', category: 'Academic Excellence' },
    { title: 'Improve study habits', category: 'Academic Excellence' },
    { title: 'Reduce procrastination', category: 'Academic Excellence' },
    { title: 'Develop better note-taking system', category: 'Academic Excellence' },
    { title: 'Create effective exam prep routine', category: 'Academic Excellence' },
  ],
  'Career Development': [
    { title: 'Land dream internship', category: 'Career Development' },
    { title: 'Build professional network', category: 'Career Development' },
    { title: 'Attend 5+ networking events', category: 'Career Development' },
    { title: 'Connect with industry mentors', category: 'Career Development' },
    { title: 'Update resume and portfolio', category: 'Career Development' },
    { title: 'Learn new technical skill', category: 'Career Development' },
    { title: 'Earn professional certification', category: 'Career Development' },
    { title: 'Complete online course', category: 'Career Development' },
    { title: 'Contribute to open source project', category: 'Career Development' },
    { title: 'Start personal project', category: 'Career Development' },
    { title: 'Attend industry conference', category: 'Career Development' },
    { title: 'Join professional organization', category: 'Career Development' },
    { title: 'Improve LinkedIn profile', category: 'Career Development' },
    { title: 'Practice interview skills', category: 'Career Development' },
    { title: 'Research career paths', category: 'Career Development' },
    { title: 'Shadow professionals in field', category: 'Career Development' },
  ],
  'Personal Growth': [
    { title: 'Read 24 books this year', category: 'Personal Growth' },
    { title: 'Learn new language', category: 'Personal Growth' },
    { title: 'Develop new hobby', category: 'Personal Growth' },
    { title: 'Practice mindfulness daily', category: 'Personal Growth' },
    { title: 'Start journaling habit', category: 'Personal Growth' },
    { title: 'Improve public speaking', category: 'Personal Growth' },
    { title: 'Take creative writing class', category: 'Personal Growth' },
    { title: 'Learn musical instrument', category: 'Personal Growth' },
    { title: 'Develop photography skills', category: 'Personal Growth' },
    { title: 'Master cooking techniques', category: 'Personal Growth' },
    { title: 'Build confidence', category: 'Personal Growth' },
    { title: 'Overcome fear', category: 'Personal Growth' },
    { title: 'Improve time management', category: 'Personal Growth' },
    { title: 'Develop leadership skills', category: 'Personal Growth' },
    { title: 'Practice gratitude daily', category: 'Personal Growth' },
    { title: 'Set healthy boundaries', category: 'Personal Growth' },
  ],
  'Health & Fitness': [
    { title: 'Exercise 4x per week', category: 'Health & Fitness' },
    { title: 'Run 5K race', category: 'Health & Fitness' },
    { title: 'Complete fitness challenge', category: 'Health & Fitness' },
    { title: 'Improve flexibility', category: 'Health & Fitness' },
    { title: 'Build strength routine', category: 'Health & Fitness' },
    { title: 'Try new sport', category: 'Health & Fitness' },
    { title: 'Eat healthier meals', category: 'Health & Fitness' },
    { title: 'Drink more water daily', category: 'Health & Fitness' },
    { title: 'Reduce sugar intake', category: 'Health & Fitness' },
    { title: 'Meal prep weekly', category: 'Health & Fitness' },
    { title: 'Get 8 hours sleep', category: 'Health & Fitness' },
    { title: 'Improve sleep schedule', category: 'Health & Fitness' },
    { title: 'Reduce screen time', category: 'Health & Fitness' },
    { title: 'Practice stress management', category: 'Health & Fitness' },
    { title: 'See therapist regularly', category: 'Health & Fitness' },
    { title: 'Take mental health days', category: 'Health & Fitness' },
  ],
  'Social & Community': [
    { title: 'Make 3 new friends', category: 'Social & Community' },
    { title: 'Strengthen existing friendships', category: 'Social & Community' },
    { title: 'Host social gathering', category: 'Social & Community' },
    { title: 'Join new club', category: 'Social & Community' },
    { title: 'Attend campus events', category: 'Social & Community' },
    { title: 'Volunteer 50 hours', category: 'Social & Community' },
    { title: 'Join volunteer organization', category: 'Social & Community' },
    { title: 'Organize charity event', category: 'Social & Community' },
    { title: 'Mentor younger student', category: 'Social & Community' },
    { title: 'Give back to community', category: 'Social & Community' },
    { title: 'Improve family relationships', category: 'Social & Community' },
    { title: 'Call parents weekly', category: 'Social & Community' },
    { title: 'Plan family visit', category: 'Social & Community' },
    { title: 'Reconnect with old friends', category: 'Social & Community' },
    { title: 'Be better listener', category: 'Social & Community' },
    { title: 'Show appreciation more', category: 'Social & Community' },
  ],
  'Financial': [
    { title: 'Create monthly budget', category: 'Financial' },
    { title: 'Track all expenses', category: 'Financial' },
    { title: 'Reduce unnecessary spending', category: 'Financial' },
    { title: 'Save $1000 emergency fund', category: 'Financial' },
    { title: 'Build 3-month savings', category: 'Financial' },
    { title: 'Start investing', category: 'Financial' },
    { title: 'Learn about stocks', category: 'Financial' },
    { title: 'Open retirement account', category: 'Financial' },
    { title: 'Pay off credit card debt', category: 'Financial' },
    { title: 'Reduce student loans', category: 'Financial' },
    { title: 'Improve credit score', category: 'Financial' },
    { title: 'Start side hustle', category: 'Financial' },
    { title: 'Freelance regularly', category: 'Financial' },
    { title: 'Sell unused items', category: 'Financial' },
    { title: 'Learn financial literacy', category: 'Financial' },
    { title: 'Meet with financial advisor', category: 'Financial' },
  ],
};
